In [36]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [37]:
def preprocess(data):
    #維度
    n, d = data.shape
    #剝離X
    X = data[:, :-1]
    #偏置項1
    #X = np.c_[np.ones(n), X]
    #剝離y
    y = data[:, -1]
    
    return X, y

In [ ]:
#將網頁上的資料下載到桌面，存儲到同一個目錄下，打開命名
train = np.genfromtxt('hw4_train.dat.txt')
test = np.genfromtxt('hw4_test.dat.txt')
X_train, y_train = preprocess(train)
X_test1, y_test = preprocess(test)
#X_test
#y_test
reg = PolynomialFeatures(degree=3) 
X_test=reg.fit_transform(X_test1)
X_test

In [58]:
np.genfromtxt('hw4_train.dat.txt',skip_header=0, skip_footer=119)

array([-2.1539, -0.2103,  1.6674,  0.469 ,  0.9755, -2.9343,  1.    ])

In [ ]:
f = open("hw4_train.dat.txt","r")   #设置文件对象
for i in range(120):
    print(f.readline().strip())


In [39]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures  #用于生成多项式
x=np.arange(10).reshape(2,5) #生成三行二列数组
reg = PolynomialFeatures(degree=3) 
y=reg.fit_transform(x)
print(x)
print(y)




[[0 1 2 3 4]
 [5 6 7 8 9]]
[[  1.   0.   1.   2.   3.   4.   0.   0.   0.   0.   0.   1.   2.   3.
    4.   4.   6.   8.   9.  12.  16.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   4.   6.
    8.   9.  12.  16.   8.  12.  16.  18.  24.  32.  27.  36.  48.  64.]
 [  1.   5.   6.   7.   8.   9.  25.  30.  35.  40.  45.  36.  42.  48.
   54.  49.  56.  63.  64.  72.  81. 125. 150. 175. 200. 225. 180. 210.
  240. 270. 245. 280. 315. 320. 360. 405. 216. 252. 288. 324. 294. 336.
  378. 384. 432. 486. 343. 392. 441. 448. 504. 567. 512. 576. 648. 729.]]


In [40]:
import liblinear
from liblinear.liblinearutil import *
import scipy
#Problem 12
#cheating means use data from "Eout"
#c=1/(2*lamda)

#lamda=0.0001
m=train(y_test,X_test,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)

#lamda=0.01
m=train(y_test,X_test,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)

#lamda=1
m=train(y_test,X_test,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)

#lamda=100
m=train(y_test,X_test,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)

#lamda=10000
m=train(y_test,X_test,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)



Accuracy = 97.375% (779/800) (classification)
Accuracy = 97.375% (779/800) (classification)
Accuracy = 96.125% (769/800) (classification)
Accuracy = 94.625% (757/800) (classification)
Accuracy = 86.25% (690/800) (classification)


In [41]:

#Problem 13

#lamda=0.0001
m=train(y_train,X_train,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=0.01
m=train(y_train,X_train,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=1
m=train(y_train,X_train,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=100
m=train(y_train,X_train,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=10000
m=train(y_train,X_train,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)


Accuracy = 77.5% (155/200) (classification)
Accuracy = 77.5% (155/200) (classification)
Accuracy = 77% (154/200) (classification)
Accuracy = 75% (150/200) (classification)
Accuracy = 71% (142/200) (classification)


In [53]:
#Problem 14
#120 train 和 80val 
train1 = np.genfromtxt('hw4_train.dat1.txt')#前120筆
X_train, y_train = preprocess(train1)

#lamda=0.0001
m=train(y_train,X_train,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=0.01
m=train(y_train,X_train,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=1
m=train(y_train,X_train,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=100
m=train(y_train,X_train,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=10000
m=train(y_train,X_train,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)


Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75% (90/120) (classification)
Accuracy = 73.3333% (88/120) (classification)


In [54]:
#Problem 14
#120 train 和 80val 
train1 = np.genfromtxt('hw4_train.dat2.txt')#後80筆
X_train, y_train = preprocess(train1)

#lamda=0.0001
m=train(y_train,X_train,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=0.01
m=train(y_train,X_train,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=1
m=train(y_train,X_train,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=100
m=train(y_train,X_train,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=10000
m=train(y_train,X_train,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

Accuracy = 81.25% (65/80) (classification)
Accuracy = 81.25% (65/80) (classification)
Accuracy = 81.25% (65/80) (classification)
Accuracy = 76.25% (61/80) (classification)
Accuracy = 73.75% (59/80) (classification)


In [52]:
#lamda=0.01
m=train(y_test,X_test,'-s 0 -c 0.05 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_test,X_test,m)

Accuracy = 96.375% (771/800) (classification)


In [43]:

#Problem 15
#convert from Dtrain to D

#lamda=0.0001
m=train(y_train,X_train,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=0.01
m=train(y_train,X_train,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=1
m=train(y_train,X_train,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=100
m=train(y_train,X_train,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=10000
m=train(y_train,X_train,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)


Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75.8333% (91/120) (classification)
Accuracy = 75% (90/120) (classification)
Accuracy = 73.3333% (88/120) (classification)


In [62]:

#Problem 16
#for lamda=0.0001,0.01,1,100,10000
#40+40+40+40+40=5*40=200
train1=np.genfromtxt('hw4_train.dat.txt',skip_header=0, skip_footer=160)
X_train1, y_train = preprocess(train1)
reg = PolynomialFeatures(degree=3) 
X_train=reg.fit_transform(X_train1)
#train2=np.genfromtxt('hw4_train.dat.txt',skip_header=40, skip_footer=120)
#X_train, y_train = preprocess(train2)
#train3=np.genfromtxt('hw4_train.dat.txt',skip_header=80, skip_footer=80)
#X_train, y_train = preprocess(train3)
#train4=np.genfromtxt('hw4_train.dat.txt',skip_header=120, skip_footer=40)
#X_train, y_train = preprocess(train4)
#train5=np.genfromtxt('hw4_train.dat.txt',skip_header=160, skip_footer=0)
#X_train, y_train = preprocess(train5)

#lamda=0.0001
m=train(y_train,X_train,'-s 0 -c 5000 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=0.01
m=train(y_train,X_train,'-s 0 -c 50 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=1
m=train(y_train,X_train,'-s 0 -c 0.5 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=100
m=train(y_train,X_train,'-s 0 -c 0.005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)

#lamda=10000
m=train(y_train,X_train,'-s 0 -c 0.00005 -e 0.000001')
p_labs,p_acc,p_vals=predict(y_train,X_train,m)



Accuracy = 82.5% (33/40) (classification)
Accuracy = 82.5% (33/40) (classification)
Accuracy = 82.5% (33/40) (classification)
Accuracy = 82.5% (33/40) (classification)
Accuracy = 82.5% (33/40) (classification)
