In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt#导入模块
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()


In [20]:
#根據題目描述，產生所需的training data
n=5
i=1
data=[]

y=random.choice([-1, 1])
if y==1:
    mean = (2, 3)
    cov = [[0.6, 0], [0, 0.6]]
    data = np.random.multivariate_normal(mean, cov, 1, 'raise')
    data = np.c_[data,np.ones(1)]
if y==-1:
    mean = (0, 4)
    cov = [[0.4, 0], [0, 0.4]]
    data = np.random.multivariate_normal(mean, cov, 1, 'raise')
    data = np.c_[data,np.ones(1)*-1]

print(data)
print(data.shape[0])

[[-0.38420303  2.9820944  -1.        ]]
1


In [21]:

for i in range(199):
    y=random.choice([-1, 1])
    if y==1:
        mean = (2, 3)
        cov = [[0.6, 0], [0, 0.6]]
        data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)],0)
        #data = np.append(data,np.random.multivariate_normal(mean, cov, 1, 'raise'),0)
        #data = np.c_[data,np.ones(1)]
        
    if y==-1:
        mean = (0, 4)
        cov = [[0.4, 0], [0, 0.4]]
        data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)*-1],0)
        #data = np.append(data,np.random.multivariate_normal(mean, cov, 1, 'raise'),0)
        #data = np.c_[data,np.ones(1)*-1]
        
data = np.c_[np.ones(200), data]
print(data)



[[ 1.00000000e+00 -3.84203032e-01  2.98209440e+00 -1.00000000e+00]
 [ 1.00000000e+00 -2.37879380e-02  4.26220830e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.90398213e+00  1.98997921e+00  1.00000000e+00]
 [ 1.00000000e+00  1.18105777e+00  3.91476535e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.11163474e+00  3.00426375e+00  1.00000000e+00]
 [ 1.00000000e+00  2.57539986e-01  4.20536829e+00 -1.00000000e+00]
 [ 1.00000000e+00 -5.16555820e-01  4.15465704e+00 -1.00000000e+00]
 [ 1.00000000e+00  2.67527961e+00  2.48435813e+00  1.00000000e+00]
 [ 1.00000000e+00  2.75965859e-01  2.80606836e+00  1.00000000e+00]
 [ 1.00000000e+00 -5.07530092e-01  4.82639045e+00 -1.00000000e+00]
 [ 1.00000000e+00 -8.95666711e-01  3.99958131e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.25111736e+00  3.80326874e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.38096800e-01  3.96055816e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.24617024e+00  3.57535792e+00  1.00000000e+00]
 [ 1.00000000e+00  1.89638359e+00  2.99224392e+00  1.00000000e

In [24]:
def save_data(data,filename):
    with open(filename,'w') as file:
        for i in range(data.shape[0]):
            file.write(str(data[i,0])+','+str(data[i,1])+','+str(data[i,2])+','+str(data[i,3])+'\n')
            
def load_data(filename):
    data = []
    with open(filename,'r') as file:
        for line in file.readlines():
            data.append([ float(i) for i in line.split(',')])
    return np.array(data)

save_data(data,'trainingdataset.txt')
d = load_data('trainingdataset.txt')
print(d.shape)
#save_data(data,'testdataset.txt')
#d = load_data('testdataset.txt')

(200, 4)


In [28]:
#分离出X
X = d[:, :-1]

#從資料剝離y
y = d[:, -1]
print(y)

[-1. -1.  1. -1.  1. -1. -1.  1.  1. -1. -1.  1. -1.  1.  1. -1.  1. -1.
  1.  1.  1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1. -1. -1. -1.  1.
  1.  1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1. -1.  1. -1.  1. -1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1.
  1.  1.  1. -1.  1.  1.  1. -1.  1.  1. -1. -1. -1.  1. -1. -1. -1. -1.
  1. -1.  1. -1. -1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.
 -1. -1.  1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.  1. -1.  1. -1.
 -1.  1.  1. -1. -1.  1.  1. -1. -1. -1.  1.  1. -1.  1. -1. -1.  1. -1.
 -1. -1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1. -1.  1. -1.  1.  1. -1.
  1. -1.  1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1. -1.  1.  1.
 -1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1. -1. -1. -1.  1. -1. -1.  1.
 -1. -1.]


In [48]:
x_vals=np.linspace(0, 2, 3)
x_mat = np.mat(x_vals).T
x_tx = x_mat.T * x_mat
denom = x_tx + np.eye(np.shape(x_mat)[1])
print(denom)

[[6.]]


In [59]:
def linear_regression(x_arr, y_arr, lam=0.2):
    x_mat = np.mat(x_arr).T
    y_mat = np.mat(y_arr).T
 
    x_tx = x_mat.T * x_mat
    denom = x_tx + np.eye(np.shape(x_mat)[1]) * lam
 
    # if lam == 0.0
    if np.linalg.det(denom) == 0.0:
        print('This matrix is singular, cannot do inverse')
        return
 
    ws = denom.I * (x_mat.T * y_mat)
    return ws

In [ ]:
if __name__ == '__main__':
    x_vals = np.linspace(0, 1, 1000)
    y_vals = x_vals + np.random.normal(0, 1, 1000)
    ws = linear_regression(x_vals, y_vals)

    predict =ws
    print(predict.A[0][0])