In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
import random

def generate(n):
    data=[]
    y=random.choice([-1, 1])
    if y==1:
        mean = (2, 3)
        cov = [[0.6, 0], [0, 0.6]]
        data = np.random.multivariate_normal(mean, cov, 1, 'raise')
        data = np.c_[data,np.ones(1)]
    if y==-1:
        mean = (0, 4)
        cov = [[0.4, 0], [0, 0.4]]
        data = np.random.multivariate_normal(mean, cov, 1, 'raise')
        data = np.c_[data,np.ones(1)*-1]

    for i in range(n-1):
        y=random.choice([-1, 1])
        if y==1:
            mean = (2, 3)
            cov = [[0.6, 0], [0, 0.6]]
            data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)],0)
        if y==-1:
            mean = (0, 4)
            cov = [[0.4, 0], [0, 0.4]]
            data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)*-1],0)
    X = data[:, :-1]    
    y = data[:, -1]    
    return X, y
n=200
X, y = generate(n)



In [15]:
#Problem 13 与 Problem 14
m=100
Ein = np.array([])
#Eout = np.array([])
for i in range(m):
    X, y = generate(n)#運行Problem 13時設為200，運行Problem14時設為5000
    X = np.c_[np.ones(n), X]

    w = inv(X.T.dot(X)).dot(X.T).dot(y)

    ein = np.mean(np.sign(X.dot(w) * y) < 0 )
    Ein = np.append(Ein, ein)

'''
Eout = np.array([])
for i in range(m):
    n=5000
    X, y = generate(n)#運行Problem 13時設為200，運行Problem14時設為5000
    X = np.c_[np.ones(n), X]

    w = inv(X.T.dot(X)).dot(X.T).dot(y)

    eout = np.mean(np.sign(X.dot(w) * y) < 0 )
    Eout = np.append(Eout, eout)
'''
print(np.average(w))#13
print("\n")
#print(np.average(Ein)-np.average(Eout))#14
#這是因為Ein和Eout兩者之差的平均值等於兩者的各自平均值相減
#plt.hist(Ein)
#plt.title('Ein without feature transform')
#plt.show()

0.2093224559429242




In [49]:
#Problem 15
def preprocess(X):
    """
    添加偏置項
    """
    n = X.shape[0]
    return np.c_[np.ones(n), X]


#定義函式
def sigmoid(s):
    return 1 / (np.exp(-s) + 1)

def gradient(X, w, y):
    temp1 = - X.dot(w) * y
    temp2 = sigmoid(temp1)
    temp3 = - X * y
    grad = np.mean(temp3 * temp2, axis=0).reshape(-1, 1)

    return grad

for i in range(100):
    X, y = generate(200)
    X_train=X
    y_train=y.reshape(-1, 1)
    X_train=preprocess(X)

    X1, y1 = generate(5000)
    X_test=X1
    y_test=y1.reshape(-1, 1)
    X_test=preprocess(X1)
    #資料的組數和維度
    n, m = X_train.shape
    n1, m1 = X_test.shape
    #print(n,n1)
    #print(m,m1)
    w = np.zeros((m, 1))
    k = 0.1

    for i in range(500):
        grad = gradient(X_train, w, y_train)
        w -= k * grad

#计算标签
    y_test_pred = X_test.dot(w)
    y_test_pred[y_test_pred > 0] = 1
    y_test_pred[y_test_pred <= 0] = -1

Eout = np.mean(y_test_pred != y_test)
print(Eout)
print(w)

0.059
[[ 0.1066522 ]
 [ 3.33315739]
 [-1.09247516]]


In [48]:
w = np.zeros((m, 1))
k = 0.1

for i in range(500):
    grad = gradient(X_train, w, y_train)
    w -= k * grad

#计算标签
y_test_pred = X_test.dot(w)
y_test_pred[y_test_pred > 0] = 1
y_test_pred[y_test_pred <= 0] = -1
#计算Eout
Eout = np.mean(y_test_pred != y_test)
#求出误差
print(Eout)
print(w)

0.0588
[[ 0.54058145]
 [ 3.13973237]
 [-1.04883709]]


In [15]:
#Problem 16
def generate2(n):

    data=[]
    y=random.choice([-1, 1])
    if y==1:
        mean = (2, 3)
        cov = [[0.6, 0], [0, 0.6]]
        data = np.random.multivariate_normal(mean, cov, 1, 'raise')
        data = np.c_[data,np.ones(1)]
    if y==-1:
        mean = (0, 4)
        cov = [[0.4, 0], [0, 0.4]]
        data = np.random.multivariate_normal(mean, cov, 1, 'raise')
        data = np.c_[data,np.ones(1)*-1]

    for i in range(n-1):
        y=random.choice([-1, 1])
        if y==1:
            mean = (2, 3)
            cov = [[0.6, 0], [0, 0.6]]
            data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)],0)
        if y==-1:
            mean = (0, 4)
            cov = [[0.4, 0], [0, 0.4]]
            data = np.append(data,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)*-1],0)

    data1=[]
    y=random.choice([1])
    mean = (6, 0)
    cov = [[0.3, 0], [0, 0.1]]
    data1 = np.random.multivariate_normal(mean, cov, 1, 'raise')
    data1 = np.c_[data1,np.ones(1)]

    for i in range(19):
        mean = (6, 0)
        cov = [[0.3, 0], [0, 0.1]]
        data1 = np.append(data1,np.c_[np.random.multivariate_normal(mean, cov, 1, 'raise'),np.ones(1)],0)

    data=np.append(data,data1,0)
    X = data[:, :-1]    
    y = data[:, -1]    
    return X, y
    #return data

print(generate2(200))

(array([[-1.03975572e+00,  3.18170287e+00],
       [ 6.51043230e-01,  3.97445486e+00],
       [-4.11601590e-01,  4.43705084e+00],
       [ 1.71910674e+00,  3.20029663e+00],
       [ 2.58643739e+00,  1.54845486e+00],
       [-5.07778636e-01,  4.41858074e+00],
       [-3.96069961e-01,  3.06087709e+00],
       [-2.65001300e-01,  2.99195778e+00],
       [ 1.48077201e+00,  3.06820123e+00],
       [ 1.33346753e+00,  3.14346281e+00],
       [-5.99475848e-01,  3.38552953e+00],
       [ 2.52258725e+00,  3.21213740e+00],
       [ 2.15331287e+00,  3.34288441e+00],
       [ 1.89402344e+00,  2.60796901e+00],
       [ 3.20708306e-01,  2.19354453e+00],
       [ 5.08452486e-01,  4.69019907e+00],
       [ 5.78832456e-03,  4.64916745e+00],
       [ 7.87306579e-01,  2.33915083e+00],
       [ 2.81024415e+00,  2.03267965e+00],
       [ 1.36244451e+00,  3.14595859e+00],
       [-2.82276603e-01,  4.09838711e+00],
       [-8.04658661e-01,  2.94389222e+00],
       [-1.53542474e-01,  3.54801027e+00],
       [ 3

In [64]:
m=100

Ein = np.array([])
#Eout = np.array([])
for i in range(m):
    X, y = generate2(200)#運行Problem 13時設為200，運行Problem14時設為5000
    #n=220
    X = np.c_[np.ones(220), X]

    w = inv(X.T.dot(X)).dot(X.T).dot(y)

    ein = np.mean(np.sign(X.dot(w) * y) < 0 )
    Ein = np.append(Ein, ein)

print(np.average(Ein))#Problem 16的解1


0.08004545454545454


In [50]:
for i in range(100):
    X, y = generate2(200)
    X_train=X
    y_train=y.reshape(-1, 1)
    X_train=preprocess(X)

    X1, y1 = generate(5000)
    X_test=X1
    y_test=y1.reshape(-1, 1)
    X_test=preprocess(X1)
    #資料的組數和維度
    n, m = X_train.shape
    n1, m1 = X_test.shape
    #print(n,n1)
    #print(m,m1)
    w = np.zeros((m, 1))
    k = 0.1

    for i in range(500):
        grad = gradient(X_train, w, y_train)
        w -= k * grad

#计算标签
    y_test_pred = X_test.dot(w)
    y_test_pred[y_test_pred > 0] = 1
    y_test_pred[y_test_pred <= 0] = -1

Eout = np.mean(y_test_pred != y_test)
print(Eout)
print(w)

0.059
[[ 0.56802048]
 [ 2.8380594 ]
 [-0.94735841]]
