In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
import random
import pandas as pd
#將網頁上的資料下載到桌面，存儲到同一個目錄下，打開命名
def train():
    data = np.genfromtxt("hw3_train.dat.txt")
    X = data[:, :-1]    
    y = data[:, -1] 
    #产生数据
    #r, d = data.shape
    #獲取幾行幾列
    return X, y


def test():
    data = np.genfromtxt("hw3_test.dat.txt")
    X = data[:, :-1]    
    y = data[:, -1] 
    #产生数据
    #r, d = data.shape
    #獲取幾行幾列
    return X, y

#Problem15和Problem16
#設式中x0均為1
#Problem15
def multi_feature2(x,n,k):
  c = np.empty((x.shape[0],0)) 
  for i in range(n):
    for j in range(x.shape[1]):
      h=(x[:,j]**i)
      c=np.c_[c,h]
  return c[:,x.shape[1]-1:x.shape[1]*2-k]

#導入train和test的資料
X, y = train()
X_test, y_test = test()

#初始化
V = []#用來記錄ein-eout的值
Eout = np.array([])
Ein = np.array([])

#本例中的train集和test集的維數相等X.shape[1]=X_test.shape[1]
for i in range(X.shape[1]):
  X_poly=multi_feature2(X,2,i)#0是下標最大，減少至下標最小需要變成x.shape[1]-1

  w_poly = inv(X_poly.T.dot(X_poly)).dot(X_poly.T).dot(y)
  ein = np.mean(np.sign(X_poly.dot(w_poly) * y) < 0)
  #Ein = np.append(Ein, ein)

  X_test_poly=multi_feature2(X_test,2,i)
  eout = np.mean(np.sign(X_test_poly.dot(w_poly) * y_test) < 0)
  #Eout  = np.append(Eout, eout)
  V=np.append(V,ein-eout)
  
  #print(ein-eout)
print(V.max())
print(np.unravel_index(np.argmax(V),V.shape))#可見下標為7，即對應為fai等於3時


-0.1323333333333333
(7,)


In [256]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures  #用于生成多项式
x=np.arange(20).reshape(2,10) #生成三行二列数组
#reg = PolynomialFeatures(degree=2) 
#reg.fit_transform(x)
print(x)


def multi_feature3(x):
  c = np.empty((x.shape[0],0)) 
  for i in range(x.shape[1]):

    h=(x[:,i])
    c=np.c_[c,h]

  return c
#np.c_[np.ones(x.shape[0]),c]

list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
slice = random.sample(list, 5)
x1=x[:,slice]
print(x1)
np.c_[np.ones(x.shape[0]),x1]
#multi_feature3(x1)#0是下標最大，減少至下標最小需要變成x.shape[1]-1
#c1=x[slice]
#print(c1)
#c[:,x.shape[1]-1:x.shape[1]*2]

#x1=x[slice]
#print(x1)
#multi_feature(x,3)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 5  8  2  4  3]
 [15 18 12 14 13]]


array([[ 1.,  5.,  8.,  2.,  4.,  3.],
       [ 1., 15., 18., 12., 14., 13.]])

In [219]:
import random

#print(random.randint(0,9))

list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
slice = random.sample(list, 5)   #从list中随机获取5个元素，作为一个片断返回 
print(slice) 
print(list)#原有序列并没有改变。 

[3, 8, 10, 7, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [163]:
import numpy as np
data=np.random.random(size=10)
print(data)
index_1=np.random.choice(data.shape[0],5,replace=False)

data1=data[index_1]

index_2=np.arange(data.shape[0])
print(index_2)
index_2=np.delete(index_2,index_1)
print(index_2)
data2=data[index_2]
data2

[0.33235665 0.72327856 0.79247964 0.59469971 0.24037455 0.96564183
 0.59829275 0.37279422 0.08789023 0.2205574 ]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 4 5]


array([0.33235665, 0.72327856, 0.79247964, 0.24037455, 0.96564183])