In [10]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
import random
import pandas as pd

In [11]:
#將網頁上的資料下載到桌面，存儲到同一個目錄下，打開命名
def train():
    data = np.genfromtxt("hw3_train.dat.txt")
    X = data[:, :-1]    
    y = data[:, -1] 
    #产生数据
    #r, d = data.shape
    #獲取幾行幾列
    return X, y


def test():
    data = np.genfromtxt("hw3_test.dat.txt")
    X = data[:, :-1]    
    y = data[:, -1] 
    #产生数据
    #r, d = data.shape
    #獲取幾行幾列
    return X, y


In [120]:
 #初始化
Eout = np.array([])
Ein = np.array([])
v = np.array([])

for n in range(200):
    X, y = train()
    list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
    slice = random.sample(list, 5)
    x1=X[:,slice]
    X_poly=np.c_[np.ones(X.shape[0]),x1]

       
    w_poly = inv(X_poly.T.dot(X_poly)).dot(X_poly.T).dot(y)

    ein = np.mean(np.sign(X_poly.dot(w_poly) * y) < 0)
    Ein = np.append(Ein, ein)

    #導入test的資料
    X_test, y_test = test()
    x2=X_test[:,slice]
    X_test_poly=np.c_[np.ones(X_test.shape[0]),x2] 

    eout = np.mean(np.sign(X_test_poly.dot(w_poly) * y_test) < 0)
    Eout  = np.append(Eout, eout)
    if n==199:
        print(np.mean(Ein-Eout))
    



-0.2175116666666667


In [12]:
#Problem12，Problem13和Problem14
def multi_feature1(x,n):
  c = np.empty((x.shape[0],0)) 
  for i in range(n+1):
    for j in range(x.shape[1]):
      h=(x[:,j]**i)
      c=np.c_[c,h]
  return c[:,x.shape[1]-1:]

X, y = train()

poly = PolynomialFeatures(degree=2)#Problem14
X_poly=poly.fit_transform(X)

#X_poly = multi_feature1(X,2)#problem12時置為2，problem13時置為8

#初始化
Eout = np.array([])
Ein = np.array([])

w_poly = inv(X_poly.T.dot(X_poly)).dot(X_poly.T).dot(y)

ein = np.mean(np.sign(X_poly.dot(w_poly) * y) < 0)
Ein = np.append(Ein, ein)

#導入test的資料
X_test, y_test = test()
#X_test_poly = multi_feature1(X_test,2)#problem12時置為2，problem13時置為8
X_test_poly = poly.fit_transform(X_test)#Problem14
eout = np.mean(np.sign(X_test_poly.dot(w_poly) * y_test) < 0)
Eout  = np.append(Eout, eout)
    
print(Ein-Eout)

[-0.33866667]


In [4]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures  #用于生成多项式
x=np.arange(2).reshape(1,2) #生成三行二列数组
reg = PolynomialFeatures(degree=2) 
reg.fit_transform(x)
#print(x)

array([[1., 0., 1., 0., 0., 1.]])

In [5]:
def multi_feature(x,n):
  c = np.empty((x.shape[0],0)) #np.empty((3,1))并不会生成一个3行1列的空数组,np.empty((3,0))才会生成3行1列空数组
  for i in range(n+1):
    for m in range(i,-1,-1):
      h=(x[:,0]**m) * (x[:,1]**(i-m))
      c=np.c_[c,h]
  return c

multi_feature(x,2)

array([[1., 0., 1., 0., 0., 1.]])

In [6]:
print('n=4时，sklearn的输出是：')
reg = PolynomialFeatures(degree=2) 
print(reg.fit_transform(x))
print('\n')

#对比
print('n=4时，函数的输出是：')
print(multi_feature(x,2))

n=4时，sklearn的输出是：
[[1. 0. 1. 0. 0. 1.]]


n=4时，函数的输出是：
[[1. 0. 1. 0. 0. 1.]]


In [8]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures  #用于生成多项式
x=np.arange(8).reshape(2,4) #生成三行二列数组
#reg = PolynomialFeatures(degree=2) 
#reg.fit_transform(x)
print(x)

def multi_feature(x,n):
  c = np.empty((x.shape[0],0)) #np.empty((3,1))并不会生成一个3行1列的空数组,np.empty((3,0))才会生成3行1列空数组
  for i in range(n+1):
    for m in range(i,-1,-1):
      h=(x[:,0]**m) * (x[:,1]**(i-m))
      c=np.c_[c,h]
  return c

print(x.shape[1])
def multi_feature2(x,n,k):
  c = np.empty((x.shape[0],0)) 
  for i in range(n):
    for j in range(x.shape[1]):
      h=(x[:,j]**i)
      c=np.c_[c,h]
  return c[:,x.shape[1]-1:x.shape[1]*2-k]

multi_feature2(x,2,0)#0是下標最大，減少至下標最小需要變成x.shape[1]-1
#multi_feature(x,3)

[[0 1 2 3]
 [4 5 6 7]]
4


array([[1., 0., 1., 2., 3.],
       [1., 4., 5., 6., 7.]])

In [95]:
#Problem15和Problem16
#設式中x0均為1
#Problem15
def multi_feature2(x,n,k):
  c = np.empty((x.shape[0],0)) 
  for i in range(n):
    for j in range(x.shape[1]):
      h=(x[:,j]**i)
      c=np.c_[c,h]
  return c[:,x.shape[1]-1:x.shape[1]*2-k]

#導入train和test的資料
X, y = train()
X_test, y_test = test()

#初始化
V = []#用來記錄ein-eout的值
Eout = np.array([])
Ein = np.array([])

#本例中的train集和test集的維數相等X.shape[1]=X_test.shape[1]
for i in range(X.shape[1]):
  X_poly=multi_feature2(X,2,i)#0是下標最大，減少至下標最小需要變成x.shape[1]-1

  w_poly = inv(X_poly.T.dot(X_poly)).dot(X_poly.T).dot(y)
  ein = np.mean(np.sign(X_poly.dot(w_poly) * y) < 0)
  #Ein = np.append(Ein, ein)

  X_test_poly=multi_feature2(X_test,2,i)
  eout = np.mean(np.sign(X_test_poly.dot(w_poly) * y_test) < 0)
  #Eout  = np.append(Eout, eout)
  V=np.append(V,ein-eout)
  
  #print(ein-eout)
print(V)
print(V.max())
print(np.unravel_index(np.argmax(V),V.shape))#可見下標為7，即對應為fai等於3時


[-0.32266667 -0.24833333 -0.26533333 -0.26466667 -0.32233333 -0.25233333
 -0.14433333 -0.13233333 -0.13433333 -0.13666667]
-0.1323333333333333
(7,)
